language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose -f docker-compose.prod.yml build

script:
  - docker-compose -f docker-compose.prod.yml run backend sh -c "python manage.py test && flake 8"
