language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose

script:
  - docker-compose -f docker-compose.ci.yml run backend sh -c "python manage.py test -v 2 && flake8" --build
  - docker-compose -f docker-compose.ci.yml build
