version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: compose/swag.Dockerfile
    env_file:
      - .env
    volumes:
      - media:/usr/media/:ro
      - static:/usr/static/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always
