version: "3.7"
services:
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

  backend: &backend
    build:
      context: neobistime/
      dockerfile: ../compose/django.Dockerfile
    image: neobistime-backend
    env_file:
      - .env
    volumes:
      - media:/usr/src/backend/media/
      - static:/usr/src/backend/static/
      # For local development only
      - ./neobistime/:/usr/src/backend/
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.3-alpine
    restart: always

  celery-worker:
    <<: *backend
    image: celery-worker
    command: ["celery", "worker", "-A", "neobistime", "--loglevel", "INFO"]
    ports: []
    volumes:
      - ./neobistime/:/usr/src/backend/
    depends_on:
      - rabbitmq
      - db

  nginx:
    volumes:
      - media:/usr/media/:ro
      - static:/usr/static/:ro
      - ./config/local.nginx:/etc/nginx/conf.d/default.conf
    image: nginx:1.17.9-alpine
    ports:
      - 80:80
    depends_on:
      - backend


volumes:
  data:
  media:
  static:
