version: '3.7'

services:
  db:
    image: postgres:12-alpine
    env_file:
      - .env_example
    volumes:
      - neobistime_data:/var/lib/postgresql/data/
    restart: always

  backend: &backend
    build:
      context: neobistime/
      dockerfile: ../compose/django.Dockerfile
    env_file:
      - .env_example
    volumes:
      - media:/usr/src/backend/media/
      - static:/usr/src/backend/static/
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input &&
                    gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 -w 3 --log-level info neobistime.wsgi:application"
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: compose/nginx.Dockerfile
    volumes:
      - media:/usr/media/:ro
      - static:/usr/static/:ro
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always

#  front-end:
#    build:
#      context: .
#      dockerfile: ./compose/react.Dockerfile
#    depends_on:
#      - backend

volumes:
  accentuation_data:
  media:
  static: