# Generated by Django 2.2.6 on 2020-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Очки'),
        ),
    ]
