# Generated by Django 2.2.6 on 2020-08-05 14:28

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='profile_imgs/default.jpg', upload_to='profile_imgs/%department_id/%name_suname/'),
        ),
    ]
