# Generated by Django 2.2.6 on 2020-08-06 16:32

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='profile_imgs/default.jpg', upload_to='profile_imgs/'),
        ),
    ]
