# Generated by Django 2.2.6 on 2020-08-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200806_1632'),
        ('users', '0002_customuser_points'),
    ]

    operations = [
    ]
