# Generated by Django 2.2.6 on 2020-08-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200814_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Telegram Чат ID'),
        ),
    ]
