# Generated by Django 2.2.6 on 2020-07-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls',
                                    to='events.Event', verbose_name='Ивент'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
