# Generated by Django 2.2.6 on 2020-07-21 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_auto_20200722_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls',
                                       to='events.Event', verbose_name='Ивент'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls',
                                       to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
