# Generated by Django 2.2.6 on 2020-07-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_auto_20200727_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='was_on_event',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Действительно был'),
        ),
    ]
