# Generated by Django 2.2.6 on 2020-08-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_poll_was_on_event'),
        ('events', '0005_auto_20200727_1405'),
    ]

    operations = [
    ]
