# Generated by Django 2.2.6 on 2020-08-14 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='departments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
