# Generated by Django 2.2.6 on 2020-08-26 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='departments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='individual_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
