# Generated by Django 2.2.6 on 2020-09-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200826_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
